# 温馨提示:
# 不要用此插件执行需要手动关闭的程序 否则子线程将会被阻塞直到你手动关闭

# 是否在执行的shell命令前加上 "cmd /c ", 若非Windows系统(无cmd.exe)请设为 false(重要)
auto-add-prefix: true

# 若此选项为 true, 则只能执行[command-whitelist]中的shell命令
limit-command: false

# shell命令白名单 需要[limit-command]为 true
command-whitelist:
  - taskmgr
  - example
